<?php

namespace App\Models;

use Database\Factories\ProductImageFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * Class ProductImage
 *
 * This class represents an image attached to a product, which may be AI generated.
 * It extends the Eloquent Model class and uses the HasFactory and HasUuids traits.
 *
 * Properties:
 *
 * @property string $id The unique identifier for the image (UUID).
 * @property string $product_id The id of the product the image belongs to.
 * @property string $image_url The URL of the image.
 * @property bool $is_selected Whether the image is the selected one for the product.
 * @property bool $is_ai_generated Whether the image was generated by AI.
 * @property string|null $prompt The prompt used to generate the image, if any.
 * @property Carbon|null $created_at The timestamp when the image was created.
 * @property Carbon|null $updated_at The timestamp when the image was last updated.
 *
 * Relationships:
 * @property Product|null $product The product the image belongs to.
 *
 * @mixin Model
 */
class ProductImage extends Model
{
    /** @use HasFactory<ProductImageFactory> */
    use HasFactory, HasUuids;

    protected $fillable = ['product_id', 'image_url', 'is_selected', 'is_ai_generated', 'prompt'];

    /**
     * Get the attribute casts for the model.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_selected' => 'boolean',
            'is_ai_generated' => 'boolean',
        ];
    }

    /**
     * @return BelongsTo<Product, $this>
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }
}
