<?php

namespace App\Enums;

/**
 * Status of an individual translation field.
 */
enum TranslationFieldStatus: string
{
    /** Newly created or not yet reviewed. */
    case Pending = 'pending';

    /** Generated by AI or written and awaiting approval. */
    case Translated = 'translated';

    /** Reviewed and approved by an administrator. */
    case Approved = 'approved';

    public function label(): string
    {
        return match ($this) {
            self::Pending => __('app.translation_field_statuses.pending'),
            self::Translated => __('app.translation_field_statuses.translated'),
            self::Approved => __('app.translation_field_statuses.approved'),
        };
    }

    /** @return list<string> */
    public static function values(): array
    {
        return array_map(
            static fn (self $status): string => $status->value,
            self::cases(),
        );
    }
}
